# version: "3.8" # It can be removed

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    image: urielgoncalves/nginx:latest
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_started

  app:
    build:
      context: node-app
    container_name: app
    image: urielgoncalves/node-app:latest
    volumes:
      - /home/app/node_modules
      - ./node-app:/home/app # It will override the /home/app content without the anonymous volume above
    tty: true
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      timeout: 10s
      retries: 5

  db:
    #image: mysql:latest #Permission issues when mounting volume on Windows
    image: mysql:5.7.16
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

# As we are using bind mount for the volume, this is not necessary
# volumes:
#   mysql-data:
#     external: true
#   node-app:
#     external: true

networks:
  app-network:
    driver: bridge